version: "3.7"

services:

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass dfffgDFFGw44
    ports:
     - "6379:6379"
    environment:
         - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - tinet

  service-demo:
    container_name: service-demo
    build:
      context: ./service-demo
      dockerfile: ./Dockerfile.dev
    volumes:
      - './service-demo/:/usr/src/app'
    restart: on-failure
    depends_on:
      - redis
    networks:
      - tinet
  

volumes:
  redis-data:

networks:
  tinet: